New marketing site
jaredh159/gertrude-web pull request #315
Opened 2024-04-19 18:19 UTC by kiahjh

2024-04-22 13:41 UTC, kiahjh commented on site/app/(marketing)/blog/page.tsx
> +  description: `TODO: Add description`,
This still needs written

2024-04-22 13:44 UTC, kiahjh commented on site/app/(marketing)/download/page.tsx
> +  description: `TODO: Add description`,
This one too

2024-04-22 13:51 UTC, kiahjh commented on site/app/docs/page.tsx
> +const DocsHomePage: React.FC = () => <div>redirecting...</div>;
You should never see this page

2024-04-22 14:06 UTC, kiahjh commented on site/components/DepressingStatisticsBlock.tsx
> +            statistic={`37%`}
We still need to decide what to put here

2024-04-22 14:08 UTC, kiahjh commented on site/components/FeaturesBlock.tsx
> +        <div ref={firstStepRef} />
These are invisible intersection observers that trigger the carousel to rotate.

2024-04-22 14:10 UTC, kiahjh commented on site/components/MainFooter.tsx
> +        <Link href="https://github.com/jaredh159/gertrude-web" className="underline">
If we move this into the gertrude org then we'll have to change this link.

2024-04-22 14:22 UTC, kiahjh commented on site/components/TestimonialsBlock.tsx
> +const TestimonialsBlock: React.FC = () => (
It might be nice to get some more testimonials from users at some point.

2024-04-22 14:43 UTC, kiahjh commented on site/markdoc/articles/docs/getting-started.md
> +description: TODO
Still needs written

2024-04-25 16:32 UTC, jaredh159 requested changes
This is a huge amount of work, thanks so much. All of it looks so amazing. The scrolly stuff is pure wizardry.

I have another chunk of review work to do, I want to crawl around the site in a browser and check a bunch of things, so I'll probably leave some comments from that as well, so my review isn't fully _done_, but I think i'll submit these comments in case you want to address some of them.

couple non-code things i also wanted to mention:

1. 404 pages seem to be white-screening with a console error, instead of showing some kind of 404
2. we have some broken links in the docs/blog area, like for instance the iphone lockdown article, where i link to "5 things you forgot", that link is now broken. we should probably carefully check all of the markdown links
3. seems a little sub-optimal that the documentation pages don't link to the blog anywhere, not even in a footer... is there a place that would make sense? come to think of it, it might be worth having a couple other links too, like at least to the "contact" page.
4. the 3 iphone-lockdown articles i feel a little torn about. while they're not documentation for gertrude, i feel a little sad that they're only findable through the blog link. i wonder if we could find a spot for just those 3 in the docs page sidebar or something? they're pretty valuable articles. i think most of our traffic for those comes from google (which should be unnaffected if we do redirects correct, i think linking more prominently to them would be nice, if we could do it in a way that felt non-cluttery.

2024-04-25 16:32 UTC, jaredh159 commented on site/components/super-scroller-illustration/ComputerScreen.tsx
> +    {/* dock */}
yeah, wise. 👍

2024-04-25 16:32 UTC, jaredh159 commented on site/components/super-scroller-illustration/__tests__/steps.spec.ts
> +  it(`returns the step and subStep`, () => {
nice. i like the fact that the UI is so intense it needs unit tests. :)

2024-04-25 16:32 UTC, jaredh159 commented on site/markdoc/files.ts
> +): Promise<ArticleOfType<T>> {
nice typescript 👍

2024-04-25 16:32 UTC, jaredh159 commented on site/public/feature-cards/family.gif
can you check if we could somehow optimize the animated gifs keeping most of the quality but getting the filesize down? or have you already looked into that?

2024-04-25 16:36 UTC, jaredh159 commented
viewing a docs page on my phone gives me huge horizontal scrolling (at least on `keeping children safe`, maybe all)

2024-04-25 16:38 UTC, jaredh159 commented
the buttons at the bottom of the sidebar aren't quite visible on my phone, see:

![Tips for Keeping Users Safe  Gertrude Internet Filter and Parental Controls](https://github.com/jaredh159/gertrude-web/assets/7050938/fc82433a-d7ae-4131-bb7c-ec61de91a340)

2024-04-25 16:40 UTC, jaredh159 commented
i'm wondering a little bit about the lack of a persistent nav in the docs on mobile. if you scroll down to the bottom of an article, you're sort of stuck, the only way to keep reading is to scroll all the way back to the top to click the hamburger. you have any thoughts on that?

2024-04-25 16:45 UTC, jaredh159 commented
hmm... the hero block renders off-center on my phone:

![Gertrude  Mac Internet Filter, Parental Controls and Activity Monitoring](https://github.com/jaredh159/gertrude-web/assets/7050938/89c63c04-8198-465b-82c4-ba421a078d2d)

2024-04-25 16:47 UTC, jaredh159 commented
i might need to show you this on my phone, but the "peace of mind for parents" block is super easy to scroll past. like if you give one solid scroll from the top, it comes into view and goes blurry before you have a chance to read it. i wonder if we could make it "pause" a little bit and require a second thumb to move on?

2024-04-25 16:49 UTC, jaredh159 commented
in the block shown below, the content goes right to the very edge on small screens. i would think a little breathing room would be nice, unless you did that on purpose and thought it was better this way.

![Gertrude  Mac Internet Filter, Parental Controls and Activity Monitoring copy](https://github.com/jaredh159/gertrude-web/assets/7050938/b4ec3a67-3a5c-4802-b3ff-090303fd3c2a)

2024-04-25 16:52 UTC, jaredh159 commented
this padding or spacing below the content and above the footer seems a little strange to me on mobile at least... feels like it might be nice to just transition straight from the black block to the footer.

![Screenshot 2024-04-25 at 12 51 11 PM](https://github.com/jaredh159/gertrude-web/assets/7050938/e5b3f80b-c76f-418c-bd52-6d1ae4c2c9ef)

2024-04-25 16:55 UTC, jaredh159 commented
i don't think the "watch demo video" works anymore.

2024-04-25 16:56 UTC, jaredh159 commented
the "step by step guide" link at the bottom of the home page seems to link to the wrong thing.

2024-04-25 17:32 UTC, kiahjh commented on shared/tailwind/src/preset.js
> +        signature: [`Qwitcher Grypen`, ...defaultTheme.fontFamily.sans],
Nope, that was just when I had your "signature" on the Holland talk route.

2024-04-25 19:05 UTC, kiahjh commented on site/app/(marketing)/contact/page.tsx
> +        Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint
Not really... ¯\_(ツ)_/¯

2024-05-01 20:18 UTC, merged